### ISSUE TITLE
Merhaba

### ISSUE THREAD

**Issue by IntelliPerson** [HyoAkira/hyoakira#1]
öncelikle merhabalar ben xda dan hatırlayacağınız üzere dark camper uzun bir süre geliştirme işlerine ara vermiştim fakat şu 1 aylık süreçte bilgisayarımı tamir ettirip yoluma devam ettim ha3g için bir android 11 dev hata düzeltme güncellemesi hazırlıyorum bilmiyorum telegram grubunda varmısın yoksun diye varsayarak konuşacağım sp56 yani github ismiye miui56 yada ayush aj geliştirmeyi bıraktı ve grubun moderatörlüğü bana kaldı istersen moderatör ve beta derlemelerini test için göndereceğim 5 kişiden biri olabilirisin ve aynı zamanda bana bazı cpp,java v.b diller gerektiren donanım dosyaları konusunda yardımcı olabileceğine inanıyorum biliyorum fazla konuştum ama eğer teklifimi kabul edecek olursan bana şu gmail adresinden ulaşabilirsin

sided9898@gmail.com

**Comment by HyoAkira** [comment]
Dönüt yazdım, özetle yardımcı olmak isterim ama  elimde şuanda batarya yok. Donanım olmadan yardımcı olabileceksem çok daha iyi olur.
